version: '3'

volumes:
  static:
  media:
  pg_data:
  frontend_dist:

networks:
  internal:
    driver: bridge

services:
  db:
    image: postgres:13
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - internal
  backend:
    image: d2avids/lesya_and_moa:latest
    env_file: .env
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    volumes:
      - ./logs:/app/logs
      - static:/backend_static/static
      - media:/app/media
    networks:
      - internal
    environment:
      - GUNICORN_CMD_ARGS=--timeout 360
  frontend:
    image: teamcode01/lesya_and_moa_frontend:latest
    restart: always
    env_file: .env
    depends_on:
      - backend
    volumes:
      - frontend_dist:/app/src/app/dist
    networks:
      - internal
  celery_worker:
    image: d2avids/lesya_and_moa:latest
    restart: always
    env_file: .env
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./logs:/app/logs
      - media:/app/media
    depends_on:
      - backend
    networks:
      - internal
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - static:/static/
      - media:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
