# Generated by Django 5.0.6 on 2024-05-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='Верность ответа')),
                ('is_started', models.BooleanField(verbose_name='Факт прохождения задания')),
            ],
            options={
                'verbose_name': 'Ответ на задание',
                'verbose_name_plural': 'Ответы на задания',
            },
        ),
    ]
