# Generated by Django 5.0.6 on 2024-05-30 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswer',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_answers', to='users.child', verbose_name='Ребенок'),
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='children_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_answers', to='users.childrengroup', verbose_name='Группа детей'),
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tasks.task', verbose_name='Задание'),
        ),
    ]
