# Generated by Django 5.0.6 on 2024-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название задания"),
        ),
        migrations.AlterField(
            model_name="taskanswer",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="Верность ответа"),
        ),
    ]
