# Generated by Django 5.0.6 on 2024-06-02 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_child_user_id_alter_childrengroup_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="child",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="childrengroup",
            old_name="user_id",
            new_name="user",
        ),
    ]
