# Generated by Django 5.0.6 on 2024-08-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_user_id_child_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tasks_type',
            field=models.CharField(choices=[('индивидуальный', 'индивидуальный'), ('групповой', 'групповой')], max_length=20, verbose_name='Формат занятий'),
        ),
    ]
